[package]
name = "remainder-mlp"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "run_workshop_circuit"
path = "src/bin/run_workshop_circuit.rs"

[[bin]]
name = "run_soln_workshop_circuit"
path = "src/bin/run_soln_workshop_circuit.rs"

[dependencies]
ark-bn254 = "0.4.0"
ark-crypto-primitives = { version = "0.4.0", features = ["sponge"] }
ark-ff = "0.4.2"
ark-poly = "0.4.2"
ark-serialize = { version = "0.4.2", features = ["derive"] }
ark-std = { version = "0.4.0", features = ["print-trace"] }
ark-test-curves = "0.4.2"
approx = "0.5"
criterion = "0.5.1"
# derive_more = "0.99.17"
itertools = "0.11.0"
rayon = "1.7"
thiserror = "1.0.40"
tracing = "0.1.37"
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
num = "0.4.1"
ndarray = "0.15.6"
ndarray-npy = "0.8.1"
tracing-subscriber = "0.3.17"
remainder-ligero = { path = "../remainder_ligero" }
remainder-shared-types = { path = "../remainder_shared_types" }
remainder = { path = "../remainder_prover" }                    # might need this
# halo2-base = { git = "https://github.com/axiom-crypto/halo2-lib", tag = "v0.3.0-ce" } # For BN-254 from Halo2
dyn-clone = "1.0.13"
dyn-clonable = "0.9.0"
log = "0.4"
env_logger = "0.10"
pretty_env_logger = "0.5"
# chrono = "0.4.31"
chrono = "=0.4.30"
# clap = { version = "=4.2.1", features = ["derive"] }
clap = { version = "=4.3.21", features = ["derive"] }
once_cell = "1.18.0"
num-bigint = "0.4.4"
num-traits = "0.2.17"
hex = "0.4"

[dev-dependencies]

[features]
default = ["parallel"]
parallel = [
  "ark-ff/parallel",
  "ark-poly/parallel",
  "ark-std/parallel",
  "ark-crypto-primitives/parallel",
]
