pub mod soln_bias_builder;
pub mod soln_bits_are_binary_builder;
pub mod soln_bits_are_binary_circuit;
pub mod soln_circuit_builders;
pub mod soln_nn_full_circuit;
pub mod soln_partial_recomp_builder;
pub mod soln_relu_builder;
pub mod soln_workshop_dims;
pub mod soln_workshop_utils;
